name: Playwright Tests
on:
  push: # Run tests on every push
    branches: [ main, master ] # Run tests on main and master branches
  pull_request: # Run tests on every pull request
    branches: [ main, master ]
jobs: # Define jobs
  test: # Define a job named test
    name: Run Playwright Tests # Set the job name
    timeout-minutes: 60 # Set the job timeout to 60 minutes
    runs-on: ubuntu-latest # Set the job to run on the latest version of Ubuntu
    steps: # Define steps
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/* # Use the latest LTS version of Node.js
    - name: Install dependencies # Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps # Install Playwright browsers
    - name: Run Playwright tests
      run: npx playwright test # Run Playwright tests
    - uses: actions/upload-artifact@v4 # Upload test results as an artifact
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/ # Upload the test results to the playwright-report directory
        retention-days: 30 # Set the retention days to 30 days
